/// App All Images ///
library;

// ignore_for_file: constant_identifier_names

abstract class AssetValues {
  static const String appLogo = 'assets/images/app_icon.jpg'; // Changed from SVG
  static const String appLogoOld = 'assets/images/appLogo.svg.old'; // Marked for removal

  static const String Razorpay = 'assets/images/Razorpay.png';
  static const String paypal = 'assets/images/paypal.png';
  static const String lodeImage = 'assets/images/lodeImage.png';
  static const String welcome = 'assets/images/welcomeimage.png';
  static const String letsYouIn = 'assets/images/letsyouin.png';
  static const String facebookLogo = "assets/images/facebooklogo.png";
  static const String googleLogo = "assets/images/googlelogo.png";
  static const String appleLogo = "assets/images/applelogo.png";
  static const String rectangle = "assets/images/Rectangle.png";
  static const String PremiumCrown = "assets/images/PremiumCrown.png";
  static const String profile = "assets/images/profile.png";
  static const String noProfile = "assets/images/noprofile.png";
  static const String noProfile_dark = "assets/images/noprofile_Dark.png";
  static const String indianFlag = "assets/images/flagindia.jpg";
  static const String fingerprint = "assets/images/fingerprint.png";
  static const String profileDone = "assets/images/profileGroup.png";
  static const String forgotPassword = "assets/images/forgotPassword.png";
  static const String newPassword = "assets/images/newPassword.png";
  static const String passwordDone = "assets/images/passwordgroup.png";
  static const String listFrame = "assets/images/listFrame.png";
  static const String download2 = "assets/images/download2.png";
  static const String download3 = "assets/images/download3.png";
  static const String download4 = "assets/images/download4.png";
  static const String card = "assets/images/card.png";
  static const String noimage = "assets/images/noimageavailable.png";
  static const String noimage1 = "assets/images/noimage.png";
  static const String grid_landing_photo = "assets/images/grid_final.jpg";
}

abstract class IconAssetValues {
  static const String lightSearch = "assets/icons/lightSearch.png";
  static const String search = "assets/icons/Search.png";
  static const String tabhome = "assets/icons/tabhome.png";
  static const String tabdiscovery = "assets/icons/tabdiscovery.png";
  static const String tabmylist = "assets/icons/tabmylist.png";
  static const String tabdownload = "assets/icons/tabdownload.png";
  static const String tabprofile = "assets/icons/tabprofile.png";
  static const String boldFilter = "assets/icons/boldFilter.png";
  static const String redSearch = "assets/icons/redSearch.png";
  static const String castIcon = "assets/icons/CastIcon.png";
  static const String arrowLeft = "assets/icons/ArrowLeft.png";
  static const String bookmark = "assets/icons/Bookmark2.png";
  static const String send = "assets/icons/Send2.png";
  static const String star = "assets/icons/Star.png";
  static const String boldStar = "assets/icons/boldStar.png";
  static const String bulkStar = "assets/icons/bulkStar.png";
  static const String arrowRight2 = 'assets/icons/ArrowRight2.png';
  static const String boldDownload = "assets/icons/boldDownload.png";
  static const String boldPlay = "assets/icons/boldPlay.png";
  static const String moreCircle = "assets/icons/morecircle.png";
  static const String heart = "assets/icons/Heart.png";
  static const String boldHeart = "assets/icons/boldHeart.png";
  static const String boldSend = "assets/icons/boldSend.png";
  static const String cancel = "assets/icons/cancal.png";
  static const String videoSpeed = "assets/icons/videoSpeed.png";
  static const String videoCast = "assets/icons/videoCast.png";
  static const String videoMore = "assets/icons/videoMore.png";
  static const String videoVector = "assets/icons/videoVector.png";
  static const String videoVoice = "assets/icons/videoVoice.png";
  static const String videoTimer = "assets/icons/videoTimer.png";
  static const String smallArrowDown = "assets/icons/smallArrowDown.png";
  static const String delete = "assets/icons/delete.png";
  static const String boldEmail = "assets/icons/boldemail2.png";
  static const String email = "assets/icons/email.png";
  static const String boldEyeShow = "assets/icons/boldeyeShow.png";
  static const String boldEyeHide = "assets/icons/boldeyeHide.png";
  static const String boldLock = "assets/icons/boldLock.png";
  static const String edit = "assets/icons/Edit.png";
  static const String boldChat = "assets/icons/boldChat.png";
  static const String notification = "assets/icons/Notification.png";
  static const String noInternet = "assets/icons/nointernet.png";
}

abstract class ProfileAssetValues {
  static const profileimage = "assets/images/profile/profileimage.png";
  static const profileediticon = "assets/icons/profileedit.png";
  static const profilevector = "assets/icons/profilevector.png";
  static const ProfileEdit = "assets/icons/Profile.png";
  static const profileNotification = "assets/icons/Notification.png";
  static const profileDownload = "assets/icons/Download.png";
  static const profileShieldDone = "assets/icons/Shield Done.png";
  static const profileMoreCircle = "assets/icons/More Circle.png";
  static const profileShow = "assets/icons/Show.png";
  static const profileInfoSquare = "assets/icons/Info Square.png";
  static const profileDangerSquare = "assets/icons/Danger Square.png";
  static const profileLogout = "assets/icons/Logout.png";
  static const profiledone = "assets/icons/done.png";
  static const profileAutoLayoutHorizontal =
      "assets/icons/AutoLayoutHorizontal.png";
  static const profilepaypal = "assets/icons/paypal.png";
  static const profilegoogle = "assets/icons/google.png";
  static const profileapple = "assets/icons/apple.png";
  static const profileMocard12 = "assets/icons/Mocard12.png";
  static const profilegroup1 = "assets/icons/group1.png";
  static const profilemastercard = "assets/icons/mastercard.png";
  static const profilesubscribeicon = "assets/icons/subscribeicon.png";
  static const profilemessage = "assets/icons/message.png";
  static const profilecountrselecty = "assets/icons/countrselecty.png";
  static const profilearrowdown = "assets/icons/arrow-down.png";
  static const profilewifi = "assets/icons/wifi.png";
  static const profiledelete = "assets/icons/delete.png";
  static const profilevideo = "assets/icons/video.png";
  static const profilevoice = "assets/icons/voice.png";
  static const profileMore = "assets/icons/profileMoreCircle.png";
  static const arrowDown = "assets/icons/arrow-down.png";
  static const customerservice = "assets/icons/customerservice.png";
  static const whatsapp = "assets/icons/whatsapp.png";
  static const website = "assets/icons/website.png";
  static const facebook = "assets/icons/facebook.png";
  static const twitter = "assets/icons/twitter.png";
  static const Instagram = "assets/icons/Instagram.png";
}

abstract class MovixIcon {
  static const king = "assets/icons/King.png";
  static const done = "assets/icons/done.png";
  static const userBlock = "assets/Bold/Hide.svg"; // Fallback as blockUser is missing
  static const profile = 'assets/Bold/Profile.svg';
  static const notification = 'assets/Bold/Notification.svg';
  static const download = 'assets/Bold/Download.svg';
  static const helpCenter = 'assets/Bold/Info Square.svg';
  static const search = "assets/Bold/Search.svg";
  static const arrowLeft = "assets/Bold/Arrow - Left.svg";
  static const String boldArrowDown = "assets/Bold/Arrow - Down 2.svg";
  static const String facebook = "assets/icons/facebook.png";
  static const String instagram = "assets/icons/Instagram.png";
  static const String music = "assets/icons/customerservice.png";
  static const String twitter = "assets/icons/twitter.png";
  static const String whatsApp = "assets/icons/whatsapp.png";
  static const String website = "assets/icons/website.png";
  static const String google = "assets/icons/google.svg";
  static const String apple = "assets/icons/apple.png";
  static const letsYouIn = "assets/Bold/Logout.svg"; // Fallback
  static const letsYouIn_Dark = "assets/Bold/Logout.svg"; // Fallback
  static const boldEmail = "assets/Bold/Message.svg";
  static const boldLock = "assets/Bold/Lock.svg";
  static const boldChat = "assets/Bold/Chat.svg";
  static const boldPlay = "assets/Bold/Play.svg";
  static const eyeHide = "assets/Bold/Hide.svg";
  static const show = 'assets/Bold/Show.svg';
  static const email = "assets/Bold/Message.svg";
  static const createPasswordImage = "assets/Bold/Lock.svg"; // Fallback
  static const createPasswordImage_Dark = "assets/Bold/Lock.svg"; // Fallback
  static const forgetPasswordImage = "assets/Bold/Lock.svg"; // Fallback
  static const forgetPasswordImage_Dark = "assets/Bold/Lock.svg"; // Fallback
  static const String appLogo = 'assets/images/app_icon.jpg'; // Changed from SVG
  static const String appLogoOld = 'assets/images/appLogo.svg.old'; // Marked for removal

  static const String moreCircle = 'assets/Bold/More Circle.svg';
  static const String filter = 'assets/Bold/Filter.svg';
  static const String boldFilter = 'assets/Bold/Filter.svg';
  static const notFoundImage = 'assets/Bold/Image.svg'; // Fallback
  static const notFoundImage_Dark = 'assets/Bold/Image.svg'; // Fallback
  static const movieCast = 'assets/Bold/Profile.svg'; // Fallback
  static const avatarFullMovie = 'assets/Bold/Profile.svg'; // Fallback
  static const bookmark = 'assets/Bold/Bookmark.svg';
  static const boldBookmark = 'assets/Bold/Bookmark.svg';
  static const home = 'assets/Bold/Home.svg';
  static const boldHome = 'assets/Bold/Home.svg';
  static const liveTv = 'assets/Bold/liveTvBold.svg';
  static const boldLiveTv = 'assets/Bold/liveTvBold.svg';
  static const boldExplore = 'assets/Bold/Discovery.svg';
  static const explore = 'assets/Bold/Discovery.svg';
  static const send = 'assets/Bold/Send.svg';
  static const boldDownload = 'assets/Bold/Download.svg';
  static const boldProfile = 'assets/Bold/Profile.svg';
  static const emptyList = 'assets/Bold/Image.svg'; // Fallback
  static const emptyList_Dark = 'assets/Bold/Image.svg'; // Fallback
  static const delete = 'assets/Bold/Delete.svg';
  static const String smallArrowRight = 'assets/Bold/Arrow - Right 2.svg';
  static const String security = 'assets/Bold/Shield Done.svg';
  static const String language = 'assets/icons/CastIcon.png'; // Fallback
  static const String logOut = 'assets/Bold/Logout.svg';
  static const String calendar = 'assets/Bold/Calendar.svg';
  static const masterCard = 'assets/Bold/Image.svg'; // Fallback
  static const andrewAnisley = 'assets/Bold/Profile.svg'; // Fallback
  static const String wifi = 'assets/icons/wifi.png';
  static const String video = 'assets/Bold/Video.svg';
  static const String audio = 'assets/Bold/Voice.svg';
  static const String star = 'assets/Bold/Star.svg';
  static const halfBoldStar = 'assets/Bold/Star.svg'; // Fallback
  static const boldStar = 'assets/Bold/Star.svg'; // Fallback
  static const payPal = 'assets/Bold/Image.svg'; // Fallback
  static const avatar = 'assets/Bold/Profile.svg'; // Fallback
  static const drStrange = 'assets/movixIcon/Image.png'; // Fallback path, still wrong but avoiding corruption
  static const volumeOff = "assets/Bold/Voice.svg"; // Fallback
  static const volumeUp = "assets/Bold/Voice.svg"; // Fallback
  static const String unLock = "assets/Bold/Unlock.svg";
  static const String boldUnLock = "assets/Bold/Lock.svg";
  static const n10 = 'assets/Bold/Arrow - Left.svg'; // Fallback
  static const p10 = 'assets/Bold/Arrow - Right 2.svg'; // Fallback
  static const speed = 'assets/Bold/Video.svg'; // Fallback
  static const collapse = "assets/Bold/Arrow - Down 2.svg"; // Fallback
  static const String setting = "assets/Bold/Setting.svg";
  static const String server = "assets/icons/server-rack.svg";
  static const String info = "assets/Bold/Info Square.svg";
  static const String chromecast = "assets/icons/Chromecast.svg";
  static const String paper = "assets/Bold/Paper.svg";
  static const String shield_fail = "assets/Bold/Shield Fail.svg";
  static const iconPremium = "assets/Bold/Star.svg"; // Fallback
}
